Update Jenkinsfile

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -1,17 +1,13 @@
-//Jenkins Pipeline for CI/CD Integration
-
 pipeline {
     agent {
         docker {
-            image 'python:3.9'
-            args '-u root'  //run as root for sudo perrmision
+            image 'docker:latest' 
+            args '-u root -v /var/run/docker.sock:/var/run/docker.sock'
         }
     }
     
     environment {
-        DOCKERHUB_CREDENTIALS = credentials('docker-hub-creds') // Must be configured in Jenkins
-        // DOCKER_REGISTRY = 'morandan7'
-        // REPO_NAME = 'final_test'
+        DOCKERHUB_CREDENTIALS = credentials('docker-hub-creds') 
         IMAGE_TAG = "${env.BUILD_NUMBER}"
         IMAGE_NAME = 'morandan7/flask-aws-monitor'
     }
@@ -28,28 +24,25 @@ pipeline {
                 sh '''
                     pip install --upgrade pip
                     pip install flake8 bandit
-                    pip install flake8
-                    pip install bandit
                 '''
-                }
             }
+        }
 
-        //mock the tests, the download not working even with upgrade pip.  
         stage('Parallel Checks') {
             parallel {
                 stage('Linting') {
                     steps {
                         dir('docker') {
-                        echo 'Flake8 linting tests'
-                        sh 'flake8 . || true'
+                            echo 'Flake8 linting tests'
+                            sh 'flake8 . || true'
                         }
                     }
                 }
                 stage('Security') {
                     steps {
                         dir('docker') {
-                        echo 'Bandit security scan tests'
-                        sh 'bandit -r . || true'
+                            echo 'Bandit security scan tests'
+                            sh 'bandit -r . || true'
                         }
                     }   
                 }
